### ISSUE TITLE
Clean also unwatched movies

### ISSUE THREAD

**Issue by co5mo** [Anthirian/script.service.janitor#51]
will you please consider adding cleaning of unwatched items too thanks

**Comment by Anthirian** [comment]
It should be doing that already. Do you have any problems with it? If so please post a log and I'll see what I can do.

**Comment by co5mo** [comment]
Hi finally geting back to you as I need this now. Where can I specify that I need a cleanup of unwatched movies? Thanks!

**Comment by Anthirian** [comment]
Closing this issue after multiple months without providing a log file showing the problem. Feel free to open a new issue if it still persists and be sure to provide a log.
