### ISSUE TITLE
Script Error While Cleaning

### ISSUE THREAD

**Issue by skiski456** [Anthirian/script.service.janitor#60]
I've been using Janitor for a long time without a problem. It hasn't been able to run since 4 days ago, this is the debug output from the log (with file paths changed):

> 12:22:13.839 T:1492  NOTICE: Janitor: Not cleaning u"file.mkv".
12:22:13.843 T:1492  NOTICE: Janitor: Not cleaning u'file2.mkv'.
12:22:13.844 T:1492  NOTICE: Janitor: Not cleaning u'file3.mkv'.
12:22:13.844 T:1492  NOTICE: Janitor: Not cleaning u'file4.mkv'.
12:22:13.844 T:1492  NOTICE: Janitor: Not cleaning u'file5.mkv'.
12:22:13.845 T:1492  NOTICE: Janitor: Not cleaning u'file6.mkv'.
12:22:13.846 T:1492   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u2019' in position 114: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\Administrator\AppData\Roaming\Kodi\addons\script.service.janitor\service.py", line 45, in <module>
                                                autostart()
                                              File "C:\Users\Administrator\AppData\Roaming\Kodi\addons\script.service.janitor\service.py", line 31, in autostart
                                                results, _ = cleaner.clean_all()
                                              File "C:\Users\Administrator\AppData\Roaming\Kodi\addons\script.service.janitor\default.py", line 228, in clean_all
                                                cleaned_files, count, status = self.clean(video_type)
                                              File "C:\Users\Administrator\AppData\Roaming\Kodi\addons\script.service.janitor\default.py", line 148, in clean
                                                unstacked_path = self.unstack(filename)
                                              File "C:\Users\Administrator\AppData\Roaming\Kodi\addons\script.service.janitor\default.py", line 385, in unstack
                                                path = path.encode()
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 114: ordinal not in range(128)
                                            -->End of Python script error report<--
12:22:13.852 T:1492 WARNING: CPythonInvoker(2, C:\Users\Administrator\AppData\Roaming\Kodi\addons\script.service.janitor\service.py): the python script "C:\Users\Administrator\AppData\Roaming\Kodi\addons\script.service.janitor\service.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmc::Monitor,class XBMCAddon::xbmcgui::DialogProgress
12:22:18.809 T:6096 WARNING: Janitor: User canceled.
12:22:18.834 T:6096 WARNING: Previous line repeats 1 times.
12:22:18.834 T:6096 WARNING: CPythonInvoker(3, C:\Users\Administrator\AppData\Roaming\Kodi\addons\script.service.janitor\default.py): the python script "C:\Users\Administrator\AppData\Roaming\Kodi\addons\script.service.janitor\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmc::Monitor,class XBMCAddon::xbmcgui::DialogProgress

**Comment by Drakhart** [comment]
I believe this should be fixed after having merged this commit: https://github.com/Anthirian/script.service.janitor/commit/aba71059c01f740d7ebb483816018c4d3f89de4c

**Comment by skiski456** [comment]
Indeed, I had the latest version from the Kodi repository which doesn't have those changes. After using that commit it runs successfully. Thanks!

**Comment by Anthirian** [comment]
I have not had a chance to update it on the Kodi repo, but it will come soon for everyone else 😊
