### ISSUE TITLE
Crashing on unkown character - UnicodeEncodeError

### ISSUE THREAD

**Issue by ohritz** [Anthirian/script.service.janitor#62]
I hade one file with a filename containing â which was crashing janitor.
Removed the file manually and janitor works again.

see https://pastebin.com/Vf9rRdwP for log

**Comment by skiski456** [comment]
I had the same issue yesterday. It's fixed in the latest commit (but not in the kodi repository yet).

https://github.com/Anthirian/script.service.janitor/commit/aba71059c01f740d7ebb483816018c4d3f89de4c
