### ISSUE TITLE
option for using foldername instead movie name

### ISSUE THREAD

**Issue by keppo070** [Anthirian/script.service.janitor#74]
I move seen file after 30days to a SMB network share.

The move fails because the Movie Name contains a : in its name. It seems that Janitor tries to create a folder based on the movie name it would like to see an option that handles this. For example take the foldername in which the movie is located.

A movie like "Mission: Impossible - Fallout" would when moving to a SMB share.
snippet from log

18:23:48.109 T:1857024928  NOTICE: VideoInfoScanner: Starting scan ..
18:23:49.987 T:1752167328   ERROR: Create - Error( No such file or directory )
18:23:49.987 T:1752167328   ERROR: Create - Error creating smb://192.168.0.132/2bedeleted/Mission: Impossible - Fallout

**Comment by Anthirian** [comment]
Good suggestion, I hope to implement it in the future. At the moment I am quite busy moving in with my girlfriend, so it’s probably going to take some time before I get around to it.

**Comment by Anthirian** [comment]
Should be fixed after #81 was merged
