### ISSUE TITLE
Support for Kodi 18

### ISSUE THREAD

**Issue by marka65** [Anthirian/script.service.janitor#75]
When upgrading to Kodi 18, Janitor isn't compatible. Would much appreciate if it was made compatible.

Cheers for the nice add-on

![image](https://user-images.githubusercontent.com/16505919/52176172-a9778380-27fa-11e9-8d57-3a181adf30f4.png)

**Comment by vendeka** [comment]
Yes, that would be great!

Thank you for the add-on and appreciate the work you have done.
