### ISSUE TITLE
Ignoring exclusions

### ISSUE THREAD

**Issue by jgrn307** [Anthirian/script.service.janitor#80]
I have my videos organized into e.g. "movies" and "archived-movies" in different folders via smb mounts.  I want Janitor to clean "movies" but not "archived-movies" so I placed the folder in the exclusions -- but Janitor is ignoring them.

I'm not sure how to grab the text of the log from the addon, but I've added two screenshots of this behavior.
![20191205_193820](https://user-images.githubusercontent.com/730189/70294148-6ded7300-1797-11ea-92fc-0fe49b8d93a9.jpg)
![20191205_193906](https://user-images.githubusercontent.com/730189/70294214-9a08f400-1797-11ea-9c42-f822c7a9f438.jpg)

Any ideas?  This used to work great about a year ago but hasn't been working recently.

**Comment by jgrn307** [comment]
I realized I posted the same problem previously and never followed up -- it seems like your algorithm is expecting an embedded username and password when I enter the smb info (the shares are authenticated) but I'm not sure how to do that -- when I added the sources I put in the smb path, then kodi asked me for a username/password, so I never had to enter some "weird" string.  Alternatively, would you consider adding some "exclusion by source"?  I have different sources in kodi for the exclusion vs. not.

**Comment by Anthirian** [comment]
It would appear that Team Kodi at some point have made a change in the way that the paths are retrieved via the JSON-RPC API, since you are also describing that it used to work like this in the past, and I did not change anything related to this in Janitor's code either.
