### ISSUE TITLE
The recycle bin is not configured yet and Janitor cannot continue without it. Would you like to configure it now?

### ISSUE THREAD

**Issue by bakatamas** [Anthirian/script.service.janitor#91]
Installing the plugin in the latest Kodi shows a window with the text in the title. No matter if I choose yes or no, the window appears again and I cannot do anything (besides deleting the plugin folder) to get rid of it.

Is there a recycle bin outside the Janitor plugin that needs setup or is this a bug?

Please help!

**Comment by bakatamas** [comment]
Problem solved.

I had previous config settings in ~/.kodi/userdata/addon_data/script.service.janitor

After I deleted that directory and also the plugin directory (~/.kodi/addons/script.service.janitor) I needed a reboot and I could finally install Janitor and set it up properly.

Keep up the good work!

**Comment by Anthirian** [comment]
Apologies for not replying sooner. Great to hear you managed to solve the issue. Thanks for letting me know in case someone has a similar issue in the future.
