### ISSUE TITLE
Unable to add SMB share in Exclusion

### ISSUE THREAD

**Issue by S3rrrjjj** [Anthirian/script.service.janitor#92]
Kodi 19 on Windows 10
Library: Jellyfin for Kodi
USB External drive

When I click SMB in Exclusion, nothing is found. I added the local path D:\Shared Videos\Classic\TV but it started deleting files anyway. In History, it shows it's using smb://*********/wd_USB/Shared Videos/Classic/TV

How can I add the SMB share? I had no problem adding it in the Kodi File Manager but still not available in Janitor. It was working with Kodi 18.

**Comment by Anthirian** [comment]
I'm unfamiliar with Jellyfin, though I was also unable to find an exclusions folder via the SMB menu item. I did set up a named server connection through Kodi and used that as the video sources. Then after, the name I chose for the server connection showed up in the folder list when trying to add exclusions. Hope that helps.

**Comment by S3rrrjjj** [comment]
I don't know what you mean exactly by "a named server connection" but I added a node, set the SMB share as the video sources but still not available in Janitor.

**Comment by S3rrrjjj** [comment]
Fixed with Kodi 19.1
